# Generated by Django 3.1.7 on 2021-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telegram Id'),
        ),
    ]
