# Generated by Django 3.1.7 on 2021-03-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militares',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='militares',
            name='identidade',
            field=models.CharField(max_length=14),
        ),
    ]
